### ISSUE TITLE
On Mac OS X, after closing the window, then clicking the dock icon, a new window does not appear

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/node-athom-gui#10]
This is common OS X behavior.

**Comment by matjaz** [comment]
this should be handled by activate event. please debug if this event is triggered. https://github.com/athombv/node-athom-gui/blob/1301e5bf2874952cccbf7318ee2aa4b97a55902b/main.js#L87

**Comment by TheMSB** [comment]
was a reference error, fixed in 0.1.1
