### ISSUE TITLE
Wrong seperator position

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/node-athom-gui#11]
![pasted image at 2016_07_01 21_23](https://cloud.githubusercontent.com/assets/319873/16532631/68a1c562-3fd3-11e6-83be-fef6bf63d7c2.png)
Should be between 'Check for Update' and 'Athom Website'

**Comment by matjaz** [comment]
needs different position of separator depending of a platform. see https://github.com/electron/electron-api-demos/blob/master/main-process/menus/application-menu.js

**Comment by TheMSB** [comment]
fixed in release 0.1.1
