### ISSUE TITLE
Installer is threaded as security issue

### ISSUE THREAD

**Issue by nklerk** [athombv/node-athom-gui#28]
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: c:\users-----------\downloads\homeysetup-v0.1.12.exe
Location: Quarantine
Computer: NL----------
User: ---------
Action taken: Quarantine succeeded

**Comment by TheMSB** [comment]
What browser did you use to download the setup?
What OS version are you running?
What Antivirus software do you have installed?

If you downloaded the setup from nuts.athom.com I can guarantee it is not a virus, if you don't believe me all of the source code is here for you to verify.

**Comment by nklerk** [comment]
This was on a windows10 client with Symantec antivirus. I used the chrome browser to download the file but got the error on execution. It's a corporate laptop.

I have no doubt that it's safe. But if I get this false positive maybe more folks will get it.

**Comment by TheMSB** [comment]
Thanks for pointing it out. Will keep an eye on this to see if it changes.

**Comment by matjaz** [comment]
Here's a virustotal check https://www.virustotal.com/en/file/093e89c30c109ec5af70e669a44a96aec9fc22e0177a3b7dbec5fec9f386c65a/analysis/1468241721/
It's clearly false positive.
You can follow similar issue here https://github.com/electron/electron/issues/4485
Some suggest contacting AV vendors to whitelist signing certificate.

**Comment by DieterKoblenz** [comment]
Confirmed. Also activates Windows Security Screen because the developer is unknown. You should add a valid developer certificate I guess.

**Comment by TheMSB** [comment]
This should be resolved with the latest release, can anyone that had the problem confirm for me if it still persists on their system?

**Comment by TheMSB** [comment]
@nklerk @DieterKoblenz @matjaz , If any of you still experience the problems with the latest release I would appreciate it if you could give me an update. If I hear no complaints for another 4 days, I will close the issue.

**Comment by nklerk** [comment]
I Stil have issues. :-(

Symantec Endpoint Protection Version 12.1.6 reports the following upon execution:

Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: c:\users\n-------k\downloads\homeysetup-v1.0.2.exe
Location: Quarantine
Computer: N-------1
User: N-------k
Action taken: Quarantine succeeded
Date found: vrijdag 25 november 2016  10:54:06


I have filed a false-positive @ https://submit.symantec.com/false_positive/standard/
There is a checkmark for the developer of the software. so Athom reporting it might be helpfull.

My report:


  When did the detection you are reporting occur? = INSTALL
  Which product were you using when you saw this? = SEP12
  Which of the following types of detection are you reporting? = INSIGHT

  Name (person to contact) = N-------k
  Email address = n-------m
  Are you the creator or distributor of the software in question? = no

  File being uploaded = HomeySetup-v1.0.2.exe
  Download (or blocking) URL = 

  Name of the software being detected = N/A
  Name of detection given by Symantec product = N/A
  File hash or clipboard paste from product = Scan type: Auto-Protect Scan
Event: Security Risk Found
Security risk detected: WS.Reputation.1
File: c:\users\n-------k\downloads\homeysetup-v1.0.2.exe
Location: Quarantine
Computer: N-------1
User: N-------k
Action taken: Quarantine succeeded
Date found: vrijdag 25 november 2016  10:54:06

**Comment by nklerk** [comment]
I have received a responce from Symentec, The installer is now white-listed. I have checked and it is now fully working for me.

**Comment by TheMSB** [comment]
@nklerk thank you for filing the report.
