### ISSUE TITLE
Can't download desktop app

### ISSUE THREAD

**Issue by HansieNL** [athombv/node-athom-gui#29]
Use the below template where applicable.

## What OS is are you running?
Windows7

## What webbrowser did you use to download the setup/dmg file?
Chrome / Firefox

## What is the version of the setup file/ application?
 v0.1.12

## What did you expect to happen and what did actually happen?
I expected a download start.

## Steps to reproduce the problem.
Clicked "Klik here " to download setup file, but get an error message:
ERROR

The request could not be satisfied.

CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. 
Generated by cloudfront (CloudFront)
Request ID: AIJiQ-7kTENkNytSc1cL7CNvBnp3xAuKv...

**Comment by TheMSB** [comment]
Thank you for your patience, this issue should now be resolved.
