### ISSUE TITLE
Homey.on( 'my_event', ... ) does not seem to work in desktop app

### ISSUE THREAD

**Issue by mnederlof** [athombv/node-athom-gui#32]
## What OS is are you running?
Windows 10

## What webbrowser did you use to download the setup/dmg file?
Chrome

## What is the version of the setup file/ application?
ex. v1.0.2

## What did you expect to happen and what did actually happen?
When i open the settings page of the Ubiquiti UniFi app, it does not show / load the realtime events sent from the app / driver.
What actually happens is nothing... 
The settings page is using the coding example as shown on this page:
https://developers.athom.com/library/appsettings/

## Steps to reproduce the problem.
Install Ubiquiti UniFi app, and open the settings page. Debug messages should start to appear in after at most 15 seconds.

It does work when using a normal browser, but just not in the app.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
