### ISSUE TITLE
Block-line insight uses next value in stead of last value

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/node-athom-gui#34]
## What OS is are you running?
macOS Sierra

## What webbrowser did you use to download the setup/dmg file?
Chrome, but I think the app runs in safari.

## What is the version of the setup file/ application?
v1.0.3

## What did you expect to happen and what did actually happen?
**Observed**: the block-line insight is not displaying the values correctly. At least not for a Thermostat-device.
![homey thermostat](https://cloud.githubusercontent.com/assets/2014478/25041910/ee494d6c-2113-11e7-8e75-9a553de3b664.jpeg)
At 12:26, a temperature of 21 is set, but the line in the graph immediately goes down to 17.5, which is the temperature set at 12:55.

The log has these (correct) entries:
Fri Apr 14 2017 12:22:00 GMT+0200 (CEST),21
Fri Apr 14 2017 12:25:40 GMT+0200 (CEST),21
Fri Apr 14 2017 12:55:16 GMT+0200 (CEST),18

**Expected**: The line should have stayed up at 21 until 12:55 and then drop to 17.5.

## Steps to reproduce the problem.
Add a Theromstat-device and change the values

**Comment by TheMSB** [comment]
Does this issue occur only when using the desktop app or also with the browser?

**Comment by ArjanKranenburg** [comment]
Also in a browser, both Chrome and Safari (on MAC)

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
